version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: timetabledata
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: rasim2003
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
